### ISSUE TITLE
EPIC 00 - Set Up Environment

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_fe#2]
- [ ] [Add Travis CI](https://github.com/zachholcomb/good_bread_fe/projects/1#card-45925986)
- [ ] [Deploy to Heroku](https://github.com/zachholcomb/good_bread_fe/projects/1#card-45925992)
- [ ] [Add Dotenv](https://github.com/zachholcomb/good_bread_fe/projects/1#card-45925994)
