### ISSUE TITLE
EPIC 04 - Order/Shipment show pages

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_fe#35]
- [ ] Order show page
- [ ] Shipment show page
- [ ] Subscription show page?
