### ISSUE TITLE
Order Show Page

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_fe#36]
As a user, when I visit my dashboard. Each order that I see listed should all be links to individual pages for those orders.  And when I visit an order's show page, I should see the following:

- [x] A list of items including in the order
- [x] Each item's image
- [x] The order's grandtotal
- [x] The order's status
- [x] The date the order was expected to be delivered
