### ISSUE TITLE
Subscription Show Page

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_fe#37]
As a user, when I visit my dashboard. Each shipment that I see listed should all be links to individual pages for those shipments.  And when I visit an order's show page, I should see the following:

- [ ] A list of items including in the order
- [ ] Each item's image
- [ ] The order's grandtotal
- [ ] The order's status
- [ ] The date the order was expected to be delivered
