### ISSUE TITLE
EPIC 03 - Cart

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_fe#4]
- [x] [Cart Page](https://github.com/zachholcomb/good_bread_fe/projects/1#card-46940650)
- [x] [Cart Login](https://github.com/zachholcomb/good_bread_fe/projects/1#card-46940657)
- [ ] [Cart Guest Checkout](https://github.com/zachholcomb/good_bread_fe/projects/1#card-46940665)
- [x] [Cart User Checkout](https://github.com/zachholcomb/good_bread_fe/projects/1#card-46940675)
- [x] [Cart Redirect](https://github.com/zachholcomb/good_bread_fe/projects/1#card-46940724)
- [x] [Removing Items from Cart](https://github.com/zachholcomb/good_bread_fe/projects/1#card-46940760)
