### ISSUE TITLE
EPIC 06 - Admin Behaviors

### ISSUE THREAD

**Issue by zachholcomb** [zachholcomb/good_bread_fe#5]
- [ ] Admin Dashboard
- [ ] Admin Orders View
- [ ] Admin Orders Update
- [ ] Admin Item CRUD
